//localhost
### get all BOOKS

GET http://localhost:3000/books
Accept: application/json

### add new book
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
  "title": "Harry Potter and the Sorcerer's Stone",
  "author": "J.K. Rowling",
  "description": "A young wizard's journey begins.",
  "releaseYear": "1997",
  "pages": 309,
  "ISBN10": "0439708184"
}

### update reader
PUT http://localhost:3000/books/67103a99b10618d3cfd1cb6b
Content-Type: application/json

{
  
  "description": "Just another book"
  
}

### DELETE reader
DELETE  http://localhost:3000/books/67103adfb10618d3cfd1cb70